name: update
on:
  workflow_dispatch: {}

jobs:
  upgrade:
    name: Update 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: GITHUB_PATH= nix-shell --run "niv update"
      - name: detect changes
        run: '[ `git status --porcelain=v1 2>/dev/null | wc -l` -eq 0 ] && exit 1'
      - run: nix-build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: "[automation] update website"
          title: "[automation] update website"
          branch: "automation/update-website"
          labels: website update